### ISSUE TITLE
0.14 update?

### ISSUE THREAD

**Issue by DesPlaysMC** [ClearSkyTeam/ClearSky-Release#12]
nice improvements. but, wheres 0.14.0? i sorta need it

**Comment by robske110** [comment]
In the 0.14 branch

**Comment by meetloaf13** [comment]
For the n00bs of us...what do we need to do with the .14 branch files to incorporate those changes on your servers?

**Comment by aodzip** [comment]
We will make a Jenkins for this

**Comment by DesPlaysMC** [comment]
mk thank yu all

**Comment by DesPlaysMC** [comment]
btw @aodzip can i have the jenkins website address when its done? hope u dont mind

**Comment by isoz** [comment]
this is not a chatroom, my mail box is filled with this stuff
